wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.8
    start_time: 1675413390.731952
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 19
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 1
      - 2
      - 5
epochs:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.1
